spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.resend.com
    port: 465
    username: resend
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  use-management-port: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
